const { CommandInteraction, Client } = require('discord.js');
const { SlashCommandBuilder } = require('discord.js');
const Discord = require('discord.js');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('move')
        .setDescription('Move members from a voice channel to another voice channel')
        .addSubcommand(subcommand => subcommand
            .setName('all')
            .setDescription('Move all members from a voice channel to another voice channel')
            .setDescriptionLocalization('fr', 'Déplace tous les membres d\'un salon vocal vers un autre salon vocal')
            .addChannelOption(option => option.setName('from')
                .setDescription('Starting voice channel')
                .setDescriptionLocalization('fr', 'Salon vocal de départ')
                .addChannelTypes(Discord.ChannelType.GuildVoice)
                .setRequired(true)
            )
            .addChannelOption(option => option.setName('to')
                .setDescription('Destination voice channel')
                .setDescriptionLocalization('fr', 'Salon vocal de destination')
                .addChannelTypes(Discord.ChannelType.GuildVoice)
                .setRequired(true)
            )
            .addBooleanOption(option => option.setName('exclude_streamers')
                .setDescription('Exclude streamers?')
                .setDescriptionLocalization('fr', 'Exclure les streameurs ?')
                .setRequired(true)
            ).addUserOption(option => option.setName('excepted_user')
                .setDescription('User excepted')
                .setDescriptionLocalization('fr', 'Utilisateur exempté')
                .setRequired(false)
            ))
        .addSubcommand(subcommand => subcommand
            .setName('group')
            .setDescription('Move members of a role from a voice channel to another voice channel')
            .setDescriptionLocalization('fr', 'Déplace les membres d\'un rôle d\'un salon vocal vers un autre salon vocal')
            .addRoleOption(option => option.setName('role')
                .setDescription('Role to move')
                .setDescriptionLocalization('fr', 'Rôle à déplacer')
                .setRequired(true)
            )
            .addChannelOption(option => option.setName('from')
                .setDescription('Starting voice channel')
                .setDescriptionLocalization('fr', 'Salon vocal de départ')
                .addChannelTypes(Discord.ChannelType.GuildVoice)
                .setRequired(true)
            )
            .addChannelOption(option => option.setName('to')
                .setDescription('Destination voice channel')
                .setDescriptionLocalization('fr', 'Salon vocal de destination')
                .addChannelTypes(Discord.ChannelType.GuildVoice)
                .setRequired(true)
            )
            .addBooleanOption(option => option.setName('excepted_streamers')
                .setDescription('Exclude streamers?')
                .setDescriptionLocalization('fr', 'Exclure les streameurs ?')
                .setRequired(true)
            )
        )
        .addSubcommand(subcommand => subcommand
            .setName('random')
            .setDescription('Move a random number of members from a voice channel to another voice channel')
            .setDescriptionLocalization('fr', 'Déplace un nombre aléatoire de membres d\'un salon vocal vers un autre salon vocal')
            .addIntegerOption(option => option.setName('amount')
                .setDescription('Number of members to move (randomly selected)')
                .setDescriptionLocalization('fr', 'Nombre de membres à déplacer (sélection aléatoire)')
                .setMinValue(1)
                .setRequired(true)
            )
            .addChannelOption(option => option.setName('from')
                .setDescription('Starting voice channel')
                .setDescriptionLocalization('fr', 'Salon vocal de départ')
                .addChannelTypes(Discord.ChannelType.GuildVoice)
                .setRequired(true)
            )
            .addChannelOption(option => option.setName('to')
                .setDescription('Destination voice channel')
                .setDescriptionLocalization('fr', 'Salon vocal de destination')
                .addChannelTypes(Discord.ChannelType.GuildVoice)
                .setRequired(true)
            )
            .addBooleanOption(option => option.setName('exclude_streamers')
                .setDescription('Exclude streamers?')
                .setDescriptionLocalization('fr', 'Exclure les streameurs ?')
                .setRequired(true)
            )
        ).addSubcommand(subcommand => subcommand
            .setName('emergency-meeting')
            .setDescription('Move all members from every voice channel to another voice channel')
            .setDescriptionLocalization('fr', 'Déplace tous les membres de tous les salons vocaux vers un autre salon vocal')
            .addChannelOption(option => option.setName('to')
                .setDescription('Destination voice channel')
                .setDescriptionLocalization('fr', 'Salon vocal de destination')
                .addChannelTypes(Discord.ChannelType.GuildVoice)
                .setRequired(true)
            ).addBooleanOption(option => option.setName('exclude_streamers')
                .setDescription('Exclude streamers?')
                .setDescriptionLocalization('fr', 'Exclure les streameurs ?')
                .setRequired(true)
            )
            .addChannelOption(option => option.setName('excepted_channel')
                .setDescription('Excepted voice channel')
                .setDescriptionLocalization('fr', 'Salon vocal exempté')
                .addChannelTypes(Discord.ChannelType.GuildVoice)
                .setRequired(false)
            )
        ).addSubcommand(subcommand => subcommand
            .setName('empty')
            .setDescription('Kick all members from a voice channel')
            .setDescriptionLocalization('fr', 'Expulser tous les membres d\'un salon vocal')
            .addChannelOption(option => option.setName('from')
                .setDescription('Voice channel')
                .setDescriptionLocalization('fr', 'Salon vocal')
                .addChannelTypes(Discord.ChannelType.GuildVoice)
                .setRequired(true)
            )
            .addUserOption(option => option.setName('excepted_user')
                .setDescription('User excepted')
                .setDescriptionLocalization('fr', 'Utilisateur exempté')
                .setRequired(false)
            )
        ).addSubcommand(subcommand => subcommand
            .setName('split')
            .setDescription('Split a voice channel into multiple defined voice channels')
            .setDescriptionLocalization('fr', 'Diviser un salon vocal en plusieurs salons vocaux définis')
            .addChannelOption(option => option.setName('from')
                .setDescription('Starting voice channel')
                .setDescriptionLocalization('fr', 'Salon vocal de départ')
                .addChannelTypes(Discord.ChannelType.GuildVoice)
                .setRequired(true)
            ).addChannelOption(option => option.setName('to_a')
                .setDescription('Voice channel A')
                .setDescriptionLocalization('fr', 'Salon vocal A')
                .addChannelTypes(Discord.ChannelType.GuildVoice)
                .setRequired(true)
            ).addChannelOption(option => option.setName('to_b')
                .setDescription('Voice channel B')
                .setDescriptionLocalization('fr', 'Salon vocal B')
                .addChannelTypes(Discord.ChannelType.GuildVoice)
                .setRequired(true)
            ).addChannelOption(option => option.setName('to_c')
                .setDescription('Voice channel C')
                .setDescriptionLocalization('fr', 'Salon vocal C')
                .addChannelTypes(Discord.ChannelType.GuildVoice)
                .setRequired(false)
            )
            .addChannelOption(option => option.setName('to_d')
                .setDescription('Voice channel D')
                .setDescriptionLocalization('fr', 'Salon vocal D')
                .addChannelTypes(Discord.ChannelType.GuildVoice)
                .setRequired(false)
            )
        ).addSubcommand(subcommand => subcommand
            .setName('regroup')
            .setDescription('Regroup members from multiple defined voice channels into one voice channel')
            .setDescriptionLocalization('fr', 'Regrouper les membres de plusieurs salons vocaux définis dans un seul salon vocal')
            .addChannelOption(option => option.setName('from_a')
                .setDescription('Starting voice channel A')
                .setDescriptionLocalization('fr', 'Salon vocal de départ A')
                .addChannelTypes(Discord.ChannelType.GuildVoice)
                .setRequired(true)
            ).addChannelOption(option => option.setName('from_b')
                .setDescription('Starting voice channel B')
                .setDescriptionLocalization('fr', 'Salon vocal de départ B')
                .addChannelTypes(Discord.ChannelType.GuildVoice)
                .setRequired(true)
            ).addChannelOption(option => option.setName('to')
                .setDescription('Destination voice channel')
                .setDescriptionLocalization('fr', 'Salon vocal de destination')
                .addChannelTypes(Discord.ChannelType.GuildVoice)
                .setRequired(true)
            ).addChannelOption(option => option.setName('from_c')
                .setDescription('Starting voice channel C')
                .setDescriptionLocalization('fr', 'Salon vocal de départ C')
                .addChannelTypes(Discord.ChannelType.GuildVoice)
                .setRequired(false)
            ).addChannelOption(option => option.setName('from_d')
                .setDescription('Starting voice channel D')
                .setDescriptionLocalization('fr', 'Salon vocal de départ D')
                .addChannelTypes(Discord.ChannelType.GuildVoice)
                .setRequired(false)
            )
        )
    ,

    /** 
     * @param {Client} client
     * @param {CommandInteraction} interaction
     * @param {String[]} args
     */

    run: async (client, interaction, args) => {
        await interaction.deferReply({ fetchReply: true, ephemeral: true });
        client.loadSubcommands(client, interaction, args);
    },
};

 